let myNum = 10;
let myStr = "some string";
let myBool = true;
let myArr = [1, 2, 3, 4, 5];
let myObj = { first: "First name", last: "Last name" };
console.log(myNum.toFixed(2));
let decimal2 = myNum.toFixed(2);
let myBigInt = 123n;
myBigInt++;
console.log(myBigInt);
